// <auto-generated />
using System;
using AndreAirLines_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AndreAirLines_API.Migrations
{
    [DbContext(typeof(AndreAirLines_APIContext))]
    partial class AndreAirLines_APIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AndreAirLines_API.Model.Aeronave", b =>
                {
                    b.Property<string>("IdAeronave")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CapacidadeAeronave")
                        .HasColumnType("int");

                    b.Property<string>("NomeAeronave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAeronave");

                    b.ToTable("Aeronave");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Aeroporto", b =>
                {
                    b.Property<string>("Sigla")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EnderecoAeroportoIdEndereco")
                        .HasColumnType("int");

                    b.Property<string>("IdAeronave")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sigla");

                    b.HasIndex("EnderecoAeroportoIdEndereco");

                    b.ToTable("Aeroporto");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Passageiro", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnderecoIdEndereco")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.HasIndex("EnderecoIdEndereco");

                    b.ToTable("Passageiro");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Voo", b =>
                {
                    b.Property<int>("IdVoo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AeronaveIdAeronave")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DestinoSigla")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("HorarioDesembarque")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioEmbarque")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrigemSigla")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PassageiroCpf")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdVoo");

                    b.HasIndex("AeronaveIdAeronave");

                    b.HasIndex("DestinoSigla");

                    b.HasIndex("OrigemSigla");

                    b.HasIndex("PassageiroCpf");

                    b.ToTable("Voo");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Aeroporto", b =>
                {
                    b.HasOne("AndreAirLines_API.Model.Endereco", "EnderecoAeroporto")
                        .WithMany()
                        .HasForeignKey("EnderecoAeroportoIdEndereco");

                    b.Navigation("EnderecoAeroporto");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Passageiro", b =>
                {
                    b.HasOne("AndreAirLines_API.Model.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoIdEndereco");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AndreAirLines_API.Model.Voo", b =>
                {
                    b.HasOne("AndreAirLines_API.Model.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("AeronaveIdAeronave");

                    b.HasOne("AndreAirLines_API.Model.Aeroporto", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoSigla");

                    b.HasOne("AndreAirLines_API.Model.Aeroporto", "Origem")
                        .WithMany()
                        .HasForeignKey("OrigemSigla");

                    b.HasOne("AndreAirLines_API.Model.Passageiro", "Passageiro")
                        .WithMany()
                        .HasForeignKey("PassageiroCpf");

                    b.Navigation("Aeronave");

                    b.Navigation("Destino");

                    b.Navigation("Origem");

                    b.Navigation("Passageiro");
                });
#pragma warning restore 612, 618
        }
    }
}
